// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServicesGatway.Models;

#nullable disable

namespace server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260526171046_AddSeedDataFinal")]
    partial class AddSeedDataFinal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ServicesGatway.Models.Airplane", b =>
                {
                    b.Property<int>("AirplaneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AirplaneID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AirplaneId"));

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ImageURL");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SeatCount")
                        .HasColumnType("int");

                    b.Property<int>("YearOfManufacture")
                        .HasColumnType("int");

                    b.HasKey("AirplaneId")
                        .HasName("PK__Airplane__5ED76B858470A223");

                    b.ToTable("Airplane", (string)null);

                    b.HasData(
                        new
                        {
                            AirplaneId = 1,
                            Manufacturer = "Boeing",
                            Nickname = "Dreamliner",
                            SeatCount = 250,
                            YearOfManufacture = 2019
                        },
                        new
                        {
                            AirplaneId = 2,
                            Manufacturer = "Airbus",
                            Nickname = "A320neo",
                            SeatCount = 180,
                            YearOfManufacture = 2021
                        },
                        new
                        {
                            AirplaneId = 3,
                            Manufacturer = "Boeing",
                            Nickname = "737 MAX",
                            SeatCount = 200,
                            YearOfManufacture = 2023
                        },
                        new
                        {
                            AirplaneId = 4,
                            Manufacturer = "Airbus",
                            Nickname = "A330",
                            SeatCount = 300,
                            YearOfManufacture = 2015
                        },
                        new
                        {
                            AirplaneId = 5,
                            Manufacturer = "Boeing",
                            Nickname = "777",
                            SeatCount = 350,
                            YearOfManufacture = 2018
                        },
                        new
                        {
                            AirplaneId = 6,
                            Manufacturer = "Embraer",
                            Nickname = "E190",
                            SeatCount = 100,
                            YearOfManufacture = 2020
                        },
                        new
                        {
                            AirplaneId = 7,
                            Manufacturer = "Airbus",
                            Nickname = "A350",
                            SeatCount = 320,
                            YearOfManufacture = 2022
                        },
                        new
                        {
                            AirplaneId = 8,
                            Manufacturer = "Boeing",
                            Nickname = "747",
                            SeatCount = 400,
                            YearOfManufacture = 2010
                        },
                        new
                        {
                            AirplaneId = 9,
                            Manufacturer = "ATR",
                            Nickname = "72-600",
                            SeatCount = 70,
                            YearOfManufacture = 2019
                        },
                        new
                        {
                            AirplaneId = 10,
                            Manufacturer = "Airbus",
                            Nickname = "A220",
                            SeatCount = 130,
                            YearOfManufacture = 2023
                        });
                });

            modelBuilder.Entity("ServicesGatway.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CustomerID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsManager")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("CustomerId")
                        .HasName("PK__Customer__A4AE64B8D5F0CD00");

                    b.ToTable("Customer", (string)null);

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Email = "moriya@israflight.co.il",
                            FullName = "מוריה בוכריס",
                            IsManager = true,
                            Password = "admin",
                            PhoneNumber = "050-0000000"
                        },
                        new
                        {
                            CustomerId = 2,
                            Email = "hagai@example.com",
                            FullName = "Hagai Moskovich",
                            IsManager = false,
                            Password = "123",
                            PhoneNumber = "052-1234567"
                        },
                        new
                        {
                            CustomerId = 3,
                            Email = "israel@example.com",
                            FullName = "Israel Israeli",
                            IsManager = false,
                            Password = "123",
                            PhoneNumber = "054-9876543"
                        },
                        new
                        {
                            CustomerId = 4,
                            Email = "sarah@example.com",
                            FullName = "Sarah Cohen",
                            IsManager = false,
                            Password = "123",
                            PhoneNumber = "050-1112223"
                        },
                        new
                        {
                            CustomerId = 5,
                            Email = "david@example.com",
                            FullName = "David Levi",
                            IsManager = false,
                            Password = "123",
                            PhoneNumber = "053-4445556"
                        },
                        new
                        {
                            CustomerId = 6,
                            Email = "yael@example.com",
                            FullName = "Yael Golan",
                            IsManager = false,
                            Password = "123",
                            PhoneNumber = "052-7778889"
                        },
                        new
                        {
                            CustomerId = 7,
                            Email = "avi@example.com",
                            FullName = "Avi Cohen",
                            IsManager = false,
                            Password = "123",
                            PhoneNumber = "054-0001112"
                        },
                        new
                        {
                            CustomerId = 8,
                            Email = "michal@example.com",
                            FullName = "Michal Ron",
                            IsManager = false,
                            Password = "123",
                            PhoneNumber = "050-3334445"
                        },
                        new
                        {
                            CustomerId = 9,
                            Email = "dan@example.com",
                            FullName = "Dan Shapira",
                            IsManager = false,
                            Password = "123",
                            PhoneNumber = "053-6667778"
                        },
                        new
                        {
                            CustomerId = 10,
                            Email = "ruth@example.com",
                            FullName = "Ruth Katz",
                            IsManager = false,
                            Password = "123",
                            PhoneNumber = "052-9990001"
                        });
                });

            modelBuilder.Entity("ServicesGatway.Models.Flight", b =>
                {
                    b.Property<int>("FlightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FlightID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FlightId"));

                    b.Property<int>("AirplaneId")
                        .HasColumnType("int")
                        .HasColumnName("AirplaneID");

                    b.Property<string>("ArrivalAirport")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ArrivalCity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ArrivalCountry")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ArrivalDateTime")
                        .HasColumnType("datetime");

                    b.Property<int?>("AvailableSeats")
                        .HasColumnType("int");

                    b.Property<string>("DepartureAirport")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DepartureCity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DepartureCountry")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DepartureDateTime")
                        .HasColumnType("datetime");

                    b.Property<bool?>("IsSabbathLanding")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("FlightId")
                        .HasName("PK__Flight__8A9E148EAB90B873");

                    b.ToTable("Flight", null, t =>
                        {
                            t.HasTrigger("trg_SetAvailableSeats");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);

                    b.HasData(
                        new
                        {
                            FlightId = 1,
                            AirplaneId = 1,
                            ArrivalAirport = "JFK",
                            ArrivalCity = "New York",
                            ArrivalCountry = "USA",
                            ArrivalDateTime = new DateTime(2026, 6, 10, 15, 30, 0, 0, DateTimeKind.Unspecified),
                            AvailableSeats = 250,
                            DepartureAirport = "Ben Gurion",
                            DepartureCity = "Tel Aviv",
                            DepartureCountry = "Israel",
                            DepartureDateTime = new DateTime(2026, 6, 10, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSabbathLanding = false,
                            Price = 850.00m
                        },
                        new
                        {
                            FlightId = 2,
                            AirplaneId = 2,
                            ArrivalAirport = "Heathrow",
                            ArrivalCity = "London",
                            ArrivalCountry = "UK",
                            ArrivalDateTime = new DateTime(2026, 6, 12, 11, 45, 0, 0, DateTimeKind.Unspecified),
                            AvailableSeats = 180,
                            DepartureAirport = "Ben Gurion",
                            DepartureCity = "Tel Aviv",
                            DepartureCountry = "Israel",
                            DepartureDateTime = new DateTime(2026, 6, 12, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSabbathLanding = false,
                            Price = 465.56m
                        },
                        new
                        {
                            FlightId = 3,
                            AirplaneId = 3,
                            ArrivalAirport = "Ben Gurion",
                            ArrivalCity = "Tel Aviv",
                            ArrivalCountry = "Israel",
                            ArrivalDateTime = new DateTime(2026, 6, 16, 1, 30, 0, 0, DateTimeKind.Unspecified),
                            AvailableSeats = 200,
                            DepartureAirport = "CDG",
                            DepartureCity = "Paris",
                            DepartureCountry = "France",
                            DepartureDateTime = new DateTime(2026, 6, 15, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSabbathLanding = false,
                            Price = 320.90m
                        },
                        new
                        {
                            FlightId = 4,
                            AirplaneId = 6,
                            ArrivalAirport = "Fiumicino",
                            ArrivalCity = "Rome",
                            ArrivalCountry = "Italy",
                            ArrivalDateTime = new DateTime(2026, 7, 1, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            AvailableSeats = 100,
                            DepartureAirport = "Ben Gurion",
                            DepartureCity = "Tel Aviv",
                            DepartureCountry = "Israel",
                            DepartureDateTime = new DateTime(2026, 7, 1, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSabbathLanding = false,
                            Price = 250.00m
                        },
                        new
                        {
                            FlightId = 5,
                            AirplaneId = 2,
                            ArrivalAirport = "Ben Gurion",
                            ArrivalCity = "Tel Aviv",
                            ArrivalCountry = "Israel",
                            ArrivalDateTime = new DateTime(2026, 7, 5, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            AvailableSeats = 180,
                            DepartureAirport = "Brandenburg",
                            DepartureCity = "Berlin",
                            DepartureCountry = "Germany",
                            DepartureDateTime = new DateTime(2026, 7, 5, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            IsSabbathLanding = false,
                            Price = 290.50m
                        },
                        new
                        {
                            FlightId = 6,
                            AirplaneId = 5,
                            ArrivalAirport = "Suvarnabhumi",
                            ArrivalCity = "Bangkok",
                            ArrivalCountry = "Thailand",
                            ArrivalDateTime = new DateTime(2026, 8, 11, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            AvailableSeats = 350,
                            DepartureAirport = "Ben Gurion",
                            DepartureCity = "Tel Aviv",
                            DepartureCountry = "Israel",
                            DepartureDateTime = new DateTime(2026, 8, 10, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSabbathLanding = false,
                            Price = 950.00m
                        },
                        new
                        {
                            FlightId = 7,
                            AirplaneId = 4,
                            ArrivalAirport = "Ben Gurion",
                            ArrivalCity = "Tel Aviv",
                            ArrivalCountry = "Israel",
                            ArrivalDateTime = new DateTime(2026, 8, 15, 23, 45, 0, 0, DateTimeKind.Unspecified),
                            AvailableSeats = 300,
                            DepartureAirport = "Barajas",
                            DepartureCity = "Madrid",
                            DepartureCountry = "Spain",
                            DepartureDateTime = new DateTime(2026, 8, 15, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSabbathLanding = false,
                            Price = 340.00m
                        },
                        new
                        {
                            FlightId = 8,
                            AirplaneId = 9,
                            ArrivalAirport = "Eleftherios Venizelos",
                            ArrivalCity = "Athens",
                            ArrivalCountry = "Greece",
                            ArrivalDateTime = new DateTime(2026, 9, 1, 9, 15, 0, 0, DateTimeKind.Unspecified),
                            AvailableSeats = 70,
                            DepartureAirport = "Ben Gurion",
                            DepartureCity = "Tel Aviv",
                            DepartureCountry = "Israel",
                            DepartureDateTime = new DateTime(2026, 9, 1, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSabbathLanding = false,
                            Price = 150.00m
                        },
                        new
                        {
                            FlightId = 9,
                            AirplaneId = 7,
                            ArrivalAirport = "Ben Gurion",
                            ArrivalCity = "Tel Aviv",
                            ArrivalCountry = "Israel",
                            ArrivalDateTime = new DateTime(2026, 9, 10, 18, 30, 0, 0, DateTimeKind.Unspecified),
                            AvailableSeats = 320,
                            DepartureAirport = "DXB",
                            DepartureCity = "Dubai",
                            DepartureCountry = "UAE",
                            DepartureDateTime = new DateTime(2026, 9, 10, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSabbathLanding = false,
                            Price = 220.75m
                        },
                        new
                        {
                            FlightId = 10,
                            AirplaneId = 10,
                            ArrivalAirport = "Schiphol",
                            ArrivalCity = "Amsterdam",
                            ArrivalCountry = "Netherlands",
                            ArrivalDateTime = new DateTime(2026, 10, 5, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            AvailableSeats = 130,
                            DepartureAirport = "Ben Gurion",
                            DepartureCity = "Tel Aviv",
                            DepartureCountry = "Israel",
                            DepartureDateTime = new DateTime(2026, 10, 5, 6, 30, 0, 0, DateTimeKind.Unspecified),
                            IsSabbathLanding = false,
                            Price = 410.00m
                        });
                });

            modelBuilder.Entity("ServicesGatway.Models.Ticket", b =>
                {
                    b.Property<int>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TicketID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TicketId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("CustomerID");

                    b.Property<int>("FlightId")
                        .HasColumnType("int")
                        .HasColumnName("FlightID");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime");

                    b.HasKey("TicketId")
                        .HasName("PK__Ticket__712CC627E69FB46E");

                    b.ToTable("Ticket", (string)null);

                    b.HasData(
                        new
                        {
                            TicketId = 1,
                            CustomerId = 2,
                            FlightId = 1,
                            PurchaseDate = new DateTime(2026, 5, 20, 9, 15, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TicketId = 2,
                            CustomerId = 3,
                            FlightId = 2,
                            PurchaseDate = new DateTime(2026, 5, 22, 14, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TicketId = 3,
                            CustomerId = 4,
                            FlightId = 3,
                            PurchaseDate = new DateTime(2026, 5, 23, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TicketId = 4,
                            CustomerId = 5,
                            FlightId = 4,
                            PurchaseDate = new DateTime(2026, 6, 1, 8, 45, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TicketId = 5,
                            CustomerId = 6,
                            FlightId = 5,
                            PurchaseDate = new DateTime(2026, 6, 10, 16, 20, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TicketId = 6,
                            CustomerId = 7,
                            FlightId = 6,
                            PurchaseDate = new DateTime(2026, 7, 15, 11, 10, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TicketId = 7,
                            CustomerId = 8,
                            FlightId = 7,
                            PurchaseDate = new DateTime(2026, 7, 20, 19, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TicketId = 8,
                            CustomerId = 9,
                            FlightId = 8,
                            PurchaseDate = new DateTime(2026, 8, 5, 12, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TicketId = 9,
                            CustomerId = 10,
                            FlightId = 9,
                            PurchaseDate = new DateTime(2026, 8, 25, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TicketId = 10,
                            CustomerId = 2,
                            FlightId = 10,
                            PurchaseDate = new DateTime(2026, 9, 2, 14, 15, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
